### ISSUE TITLE
Deleted file does are shown within the virtual folder

### ISSUE THREAD

**Issue by skjnldsv** [icewind1991/virtualfolder#4]
![image](https://user-images.githubusercontent.com/14975046/129693837-4a952ab8-deb8-4987-aba1-7c4018cc6299.png)

Shall we just hide them? In case they get restored?
Delete them in case there is no trashbin enabled?

**Comment by icewind1991** [comment]
Should we delete the folder if the last item in it is deleted or just keep the empty folder?

**Comment by skjnldsv** [comment]
I think not. I think that should be a manual action :thinking:

**Comment by icewind1991** [comment]
https://github.com/icewind1991/virtualfolder/commit/a0f9b1811f0742036b4d386ef71cb8513e82fd6c
