### ISSUE TITLE
Should we catch dav COPY and MOVE to automatically update a virtual folder?

### ISSUE THREAD

**Issue by skjnldsv** [icewind1991/virtualfolder#7]
If we want to try to stick t o dav, having the folders writable and supporting COPY/MOVE and not CREATE could be a way?

**Comment by skjnldsv** [comment]
Can we deny CREATE for new files and only catch MOVE/COPY?

**Comment by icewind1991** [comment]
Implementing the behavior shouldn't be an issue but that would lead to confusion for users where folders look writable but trying to upload anything to it fails.

(for cases where the user can see the folder)
